job_id: tree-pruner-86aab5fb-b4fe-4792-b81e-365952880b9c
email: alec.b.luro@gmail.com
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Turdus_albicollis, Turdus_albocinctus, Turdus_amaurochalinus, Turdus_assimilis,
  Turdus_aurantius, Turdus_bewsheri, Turdus_boulboul, Turdus_cardis, Turdus_celaenops,
  Turdus_chiguanco, Turdus_chrysolaus, Turdus_daguae, Turdus_dissimilis, Turdus_falcklandii,
  Turdus_feae, Turdus_flavipes, Turdus_fulviventris, Turdus_fumigatus, Turdus_fuscater,
  Turdus_grayi, Turdus_hauxwelli, Turdus_helleri, Turdus_hortulorum, Turdus_ignobilis,
  Turdus_iliacus, Turdus_infuscatus, Turdus_jamaicensis, Turdus_kessleri, Turdus_lawrencii,
  Turdus_leucomelas, Turdus_leucops, Turdus_lherminieri, Turdus_libonyanus, Turdus_ludoviciae,
  Turdus_maculirostris, Turdus_maranonicus, Turdus_menachensis, Turdus_merula, Turdus_migratorius,
  Turdus_mupinensis, Turdus_naumanni, Turdus_nigrescens, Turdus_nigriceps, Turdus_nudigenis,
  Turdus_obscurus, Turdus_obsoletus, Turdus_olivaceofuscus, Turdus_olivaceus, Turdus_olivater,
  Turdus_pallidus, Turdus_pelios, Turdus_philomelos, Turdus_pilaris, Turdus_plebejus,
  Turdus_plumbeus, Turdus_poliocephalus, Turdus_reevei, Turdus_rubrocanus, Turdus_ruficollis,
  Turdus_rufitorques, Turdus_rufiventris, Turdus_rufopalliatus, Turdus_serranus, Turdus_subalaris,
  Turdus_swalesi, Turdus_tephronotus, Turdus_torquatus, Turdus_unicolor, Turdus_viscivorus,
  Psophocichla litsitsirupa]
sample_trees: [EricsonStage2Full_7074.tre, EricsonStage2Full_1910.tre, EricsonStage2Full_6984.tre,
  EricsonStage2Full_9962.tre, EricsonStage2Full_2577.tre, EricsonStage2Full_2578.tre,
  EricsonStage2Full_7743.tre, EricsonStage2Full_3556.tre, EricsonStage2Full_6203.tre,
  EricsonStage2Full_9202.tre, EricsonStage2Full_0423.tre, EricsonStage2Full_9424.tre,
  EricsonStage2Full_8336.tre, EricsonStage2Full_1221.tre, EricsonStage2Full_9364.tre,
  EricsonStage2Full_7928.tre, EricsonStage2Full_7880.tre, EricsonStage2Full_2018.tre,
  EricsonStage2Full_9765.tre, EricsonStage2Full_8484.tre, EricsonStage2Full_6098.tre,
  EricsonStage2Full_9846.tre, EricsonStage2Full_7553.tre, EricsonStage2Full_8541.tre,
  EricsonStage2Full_5616.tre, EricsonStage2Full_6211.tre, EricsonStage2Full_2705.tre,
  EricsonStage2Full_0451.tre, EricsonStage2Full_1154.tre, EricsonStage2Full_9579.tre,
  EricsonStage2Full_8853.tre, EricsonStage2Full_8138.tre, EricsonStage2Full_9667.tre,
  EricsonStage2Full_5891.tre, EricsonStage2Full_6562.tre, EricsonStage2Full_7779.tre,
  EricsonStage2Full_0067.tre, EricsonStage2Full_5694.tre, EricsonStage2Full_8810.tre,
  EricsonStage2Full_5285.tre, EricsonStage2Full_1203.tre, EricsonStage2Full_7975.tre,
  EricsonStage2Full_5450.tre, EricsonStage2Full_1712.tre, EricsonStage2Full_9835.tre,
  EricsonStage2Full_4500.tre, EricsonStage2Full_8597.tre, EricsonStage2Full_1689.tre,
  EricsonStage2Full_4199.tre, EricsonStage2Full_4823.tre, EricsonStage2Full_3437.tre,
  EricsonStage2Full_4755.tre, EricsonStage2Full_9459.tre, EricsonStage2Full_2530.tre,
  EricsonStage2Full_2641.tre, EricsonStage2Full_8779.tre, EricsonStage2Full_4300.tre,
  EricsonStage2Full_8744.tre, EricsonStage2Full_1991.tre, EricsonStage2Full_2038.tre,
  EricsonStage2Full_0248.tre, EricsonStage2Full_3142.tre, EricsonStage2Full_4387.tre,
  EricsonStage2Full_7628.tre, EricsonStage2Full_0494.tre, EricsonStage2Full_2501.tre,
  EricsonStage2Full_4825.tre, EricsonStage2Full_8339.tre, EricsonStage2Full_3553.tre,
  EricsonStage2Full_8263.tre, EricsonStage2Full_3143.tre, EricsonStage2Full_4333.tre,
  EricsonStage2Full_3885.tre, EricsonStage2Full_9723.tre, EricsonStage2Full_0076.tre,
  EricsonStage2Full_3433.tre, EricsonStage2Full_4673.tre, EricsonStage2Full_4059.tre,
  EricsonStage2Full_8054.tre, EricsonStage2Full_7966.tre, EricsonStage2Full_0960.tre,
  EricsonStage2Full_0458.tre, EricsonStage2Full_3004.tre, EricsonStage2Full_7984.tre,
  EricsonStage2Full_2079.tre, EricsonStage2Full_3198.tre, EricsonStage2Full_7774.tre,
  EricsonStage2Full_0072.tre, EricsonStage2Full_3734.tre, EricsonStage2Full_4739.tre,
  EricsonStage2Full_2013.tre, EricsonStage2Full_2008.tre, EricsonStage2Full_9996.tre,
  EricsonStage2Full_5974.tre, EricsonStage2Full_8807.tre, EricsonStage2Full_6180.tre,
  EricsonStage2Full_2717.tre, EricsonStage2Full_9554.tre, EricsonStage2Full_7329.tre,
  EricsonStage2Full_4469.tre]
status: COMPLETED
created_at: 2019-02-28T20:29:56Z
completed_at: 2019-02-28T20:31:23Z
bad_names: {EricsonStage2Full_0067.tre: [Psophocichla litsitsirupa], EricsonStage2Full_0072.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_0076.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_0248.tre: [Psophocichla litsitsirupa], EricsonStage2Full_0423.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_0451.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_0458.tre: [Psophocichla litsitsirupa], EricsonStage2Full_0494.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_0960.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_1154.tre: [Psophocichla litsitsirupa], EricsonStage2Full_1203.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_1221.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_1689.tre: [Psophocichla litsitsirupa], EricsonStage2Full_1712.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_1910.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_1991.tre: [Psophocichla litsitsirupa], EricsonStage2Full_2008.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_2013.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_2018.tre: [Psophocichla litsitsirupa], EricsonStage2Full_2038.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_2079.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_2501.tre: [Psophocichla litsitsirupa], EricsonStage2Full_2530.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_2577.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_2578.tre: [Psophocichla litsitsirupa], EricsonStage2Full_2641.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_2705.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_2717.tre: [Psophocichla litsitsirupa], EricsonStage2Full_3004.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_3142.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_3143.tre: [Psophocichla litsitsirupa], EricsonStage2Full_3198.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_3433.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_3437.tre: [Psophocichla litsitsirupa], EricsonStage2Full_3553.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_3556.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_3734.tre: [Psophocichla litsitsirupa], EricsonStage2Full_3885.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_4059.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_4199.tre: [Psophocichla litsitsirupa], EricsonStage2Full_4300.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_4333.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_4387.tre: [Psophocichla litsitsirupa], EricsonStage2Full_4469.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_4500.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_4673.tre: [Psophocichla litsitsirupa], EricsonStage2Full_4739.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_4755.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_4823.tre: [Psophocichla litsitsirupa], EricsonStage2Full_4825.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_5285.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_5450.tre: [Psophocichla litsitsirupa], EricsonStage2Full_5616.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_5694.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_5891.tre: [Psophocichla litsitsirupa], EricsonStage2Full_5974.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_6098.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_6180.tre: [Psophocichla litsitsirupa], EricsonStage2Full_6203.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_6211.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_6562.tre: [Psophocichla litsitsirupa], EricsonStage2Full_6984.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_7074.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_7329.tre: [Psophocichla litsitsirupa], EricsonStage2Full_7553.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_7628.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_7743.tre: [Psophocichla litsitsirupa], EricsonStage2Full_7774.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_7779.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_7880.tre: [Psophocichla litsitsirupa], EricsonStage2Full_7928.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_7966.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_7975.tre: [Psophocichla litsitsirupa], EricsonStage2Full_7984.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_8054.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_8138.tre: [Psophocichla litsitsirupa], EricsonStage2Full_8263.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_8336.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_8339.tre: [Psophocichla litsitsirupa], EricsonStage2Full_8484.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_8541.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_8597.tre: [Psophocichla litsitsirupa], EricsonStage2Full_8744.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_8779.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_8807.tre: [Psophocichla litsitsirupa], EricsonStage2Full_8810.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_8853.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_9202.tre: [Psophocichla litsitsirupa], EricsonStage2Full_9364.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_9424.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_9459.tre: [Psophocichla litsitsirupa], EricsonStage2Full_9554.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_9579.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_9667.tre: [Psophocichla litsitsirupa], EricsonStage2Full_9723.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_9765.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_9835.tre: [Psophocichla litsitsirupa], EricsonStage2Full_9846.tre: [
    Psophocichla litsitsirupa], EricsonStage2Full_9962.tre: [Psophocichla litsitsirupa],
  EricsonStage2Full_9996.tre: [Psophocichla litsitsirupa]}
