
%%{init: {'theme':'base', 'themeVariables':{'fontSize': '20px', 'textColor': 'black', 'fontFamily':'lato', 'edgeLabelBackground':'white'}}}%%

graph TD
    subgraph BTI["Breeding Timing"]
        subgraph MB["Migratory Behavior"]
            A1(Full Migration)
            A2(Partial Migration)
            A3(No Migration)
        end
        A4(Breeding Season Length)
    end

    subgraph BSY["Breeding Sympatry"]
        B1(Number of Sympatric Species)
    end

    subgraph BSP["Breeding Spacing"]
        C1(Breeding Range Size)
        subgraph LM["Landmass"]
            C2(Mainland Residency)
            C3(Island Residency)
        end
    end

    PSD{Plumage Sexual Dichromatism}
        A1--"+"-->PSD
        A2--"+"-->PSD
        A3--"-"-->PSD
        A4--"-"-->PSD
        B1--"+"-->PSD
        C1--"+"-->PSD
        C2--"+"-->PSD
        C3--"-"-->PSD

style MB fill:#e0d877, stroke:#e0d877;
style LM fill:#e0d877, stroke:#e0d877;
style BTI fill:#f2f567,stroke:gray,stroke-width:2px;
style BSY fill:#f2f567,stroke:gray,stroke-width:2px;
style BSP fill:#f2f567,stroke:gray,stroke-width:2px;
style PSD fill:#9deffa,stroke:gray,stroke-width:2px;

linkStyle 0 stroke-width:4px,stroke:blue;
linkStyle 1 stroke-width:4px,stroke:blue;
linkStyle 2 stroke-width:4px,stroke:red;
linkStyle 3 stroke-width:4px,stroke:red;
linkStyle 4 stroke-width:4px,stroke:blue;
linkStyle 5 stroke-width:4px,stroke:blue;
linkStyle 6 stroke-width:4px,stroke:blue;
linkStyle 7 stroke-width:4px,stroke:red;  
